Fix type conflict caused by global export of Chai by Cypress.
The conflict occurs because both Jest and Chai(a Cypress dependency) declare a global "Assertion" type. Under certain conditions the Chai version takes precedence, and results in the type error. For example: "src/algorithms/test/run.test.tsx:42:20 - error TS2339: Property 'toBeObject' does not exist on type 'Assertion'."

This fix works by excluding the cypress/ folder from tsconfig, thereby keeping the unecessary Chai defintions out of the global namespace.